deep-ink-ventures/genesis-dao-frontend

- .eslintrc
- src/components/IssueTokensForm.tsx
- src/components/LoadingModal.tsx
- src/components/NotificationToast.tsx
- src/components/WalletConnect.tsx
- src/hooks/useGenesisDao.ts
- src/pages/dao/[daoId]/index.tsx
- src/pages/explore.tsx
- src/pages/index.tsx
- src/pages/manage.tsx
- src/stores/genesisStore.ts
- src/styles/global.css
- src/templates/MainLayout.tsx
Also fixed a few things and some based on Parity feedback
> feat: add homepage background

- src/components/FaultyModal.tsx
Fixed max character validation key
POT:
> fix: Proposal report description limit

- src/components/CouncilTokens.tsx
> fix: fixed add council member input alignment

- src/components/Congratulations.tsx
> fix: fixed DAO name on success page

- src/stores/genesisStore.ts
added zustand inspector dev tool to improve dev experience 
**Please install Redux devtool browser extension**
POT:
> zustand inspector dev tool

- src/components/Assets.tsx
- src/components/AssetsTable.tsx
- src/pages/account/index.tsx
- src/services/assets.ts
- src/services/daos.ts
- src/stores/genesisStore.ts
- src/types/response.ts
> My Assets Integration

- src/pages/dao/[daoId]/create-proposal.tsx
update label text and add spacing
POT:
>  Improve proposal creation page

- src/components/Assets.tsx
- src/components/AssetsTable.tsx
- src/components/Pagination.tsx
- src/services/assets.ts
POT: 
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/01175956-f6bb-4470-9f07-4e84e9b5519c
> My Assets Pagination and Client Side Search

- src/components/Assets.tsx
- src/components/Loading.tsx
- src/components/Spinner.tsx
- src/components/Transactions.tsx
- refactor spinner size props
- added loader to Dao Transactions andMy Assets
POT:
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/23d88c54-0ccc-4fce-8a3c-cae5ff61beb1
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/7b364d0a-f89f-4535-8c76-120e88193c62
> DAO Transactions and My Assets Loader

- src/components/Transactions.tsx
fix toggling accordon collapse state
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/43b9a76f-8717-4cf1-928d-396deef99546
> Transaction Accordion Expand Toggle

- src/components/TransactionAccordion.tsx
- src/components/Transactions.tsx
POT:
load transactions on wallet connect.
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/5196a00f-5ef2-40d2-95b5-a2b08a90b014
optimize accordion expand toggle.
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/e38ef871-3ff8-4139-b176-dafbf7160f3a
> Transction Accordion Fixes

- __test__/CreateProposal.test.tsx
- src/components/DaoDashboard.tsx
- src/stores/genesisStore.ts
TODO:
- Integrate week increase/decrease percentage
> Integrate Dao Dashboard Stat Widget Values

- src/components/DaoDashboard.tsx
- src/components/StatusCard.tsx
remove stat widget footer 
POT:
> Remove Stat Widget Footer

- src/stores/genesisStore.ts
- map BigNumber if proposal_token_deposit is not null
> New Proposal Exception Fix

- src/components/DaoDashboard.tsx
redirect see all to proposals page
POT:
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/8bf96aee-1496-4dfc-b13a-c102bd7c40c8
> See All Proposals Redirect

- src/components/Assets.tsx
added admin and token holder filter to Assets page
POT:
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/5c6b964b-92d9-46fa-ae0f-c2e179f96155
> Assets Admin Filter

- __test__/Assets.test.tsx
- __test__/AssetsTable.test.tsx
- src/components/Assets.tsx
- src/components/AssetsTable.tsx
- src/stores/account.ts
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/2eebb3ba-6624-42ab-af48-b6eed4ad5713
> My Assets Admin Badge Fix

- __test__/TransferAssetModal.test.tsx
- src/components/TransferAssetModal.tsx
- src/hooks/useGenesisDao.ts
- src/pages/account/index.tsx
- src/stores/account.ts
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/cf9fd2bb-05c2-4234-a510-f84c7d90c807
> Integrate Asset Transfer Modal

- src/components/CreateDaoModal.tsx
[createdao.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/38088c2c-6c9d-4093-98f0-0a1c5c8bf126)
> Create Dao Modal Input Reset

- src/components/GovernanceForm.tsx
> Disable Custom Governance Tab

- src/pages/account/index.tsx
- src/pages/dao/[daoId]/index.tsx
- src/svg/polkadotjs.svg
POT
[polkadotjsredirect.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/8d3b5602-22af-4197-8cd1-6056b653c9a7)
> Account View PolkadotJS External Link

- src/components/CouncilTokens.tsx
> Council Tokens: Update Distribute Tokens Copy

- src/pages/account/index.tsx
[copytoclipboard.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/f205dfc2-e416-4ee6-979a-a895b4246bbd)
> Profile Page Copy Address to Clipboard

- src/components/ExploreDaos.tsx
- src/hooks/useDebounce.ts
- src/services/daos.ts
- src/stores/genesisStore.ts
- src/utils/transformer.ts
[searchdao.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/eacdb7cf-6b75-4915-a92f-f7d8b5613243)
> Explore DAO API Search 

- __test__/AssetHoldingCard.test.tsx
- src/components/AssetHoldingCard.tsx
> Asset Holding Card: Remove Unit From Balance

- src/pages/account/index.tsx
- src/svg/user-icon.svg
> Account Page User Image Placeholder

- src/pages/dao/[daoId]/index.tsx
- src/stores/genesisStore.ts
fetch dao supply and display in dao page
> Dao Treasury Balance Display

- src/pages/dao/[daoId]/index.tsx
- src/stores/genesisStore.ts
> fix treasury balance query

- src/services/multiSigTransactions.ts
- src/stores/dao.ts
added multisigtxns to dao page slice
> DAO Slice MultisigTransactions

- src/components/MultisigTransactionAccordion.tsx
- src/components/Transactions.tsx
- src/pages/dao/[daoId]/index.tsx
- src/stores/dao.ts
Updated integration POT
Non-Admin View
Admin but not first approver
Admin and first approver
> Multisig Transactions Screen

- src/components/DistributeTokensForm.tsx
- src/components/TransferAsset.tsx
> feat: disable multiple input in governance transfer asset form

- __test__/TransferAssetModal.test.tsx
- src/components/DaoDashboard.tsx
- src/components/TransferAssetModal.tsx
- src/pages/dao/[daoId]/index.tsx
[send-tokens.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/94a2d839-c7a1-469c-8de7-24917b2d44a6)
> feat: update send tokens modal

- src/components/DaoCard.tsx
> fix: reference signatories to tag admin cards

- __test__/AssetsTable.test.tsx
- src/components/AssetsTable.tsx
- src/components/DaoCard.tsx
- src/services/multiSigs.ts
update endpoint and fix admin flag in assets table
[admin-flag.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/627a6c19-3c8c-46aa-a914-8cf49a93a4ea)
> Admin Check Refactor

- src/components/ChangeDaoOwner.tsx
- src/components/CouncilMembersForm.tsx
- src/components/CouncilTokens.tsx
- src/components/CreateDaoModal.tsx
- src/components/DistributeTokensForm.tsx
- src/components/MajorityModel.tsx
- src/components/MetadataForm.tsx
- src/components/TransferForm.tsx
- src/components/TransferTreasuryAsset.tsx
- src/hooks/useGenesisDao.ts
- disable inputs and btns when txn is loading
input is disabled, the white bg in the input is added by the browser autocomplete.
> Form Loading State

- __test__/Badge.test.tsx
- src/components/Badge.tsx
- src/components/MultisigTransactionAccordion.tsx
> Multisig Transactions Badge Colors

- src/components/ProposalCard.tsx
- src/pages/dao/[daoId]/proposal/[propId]/index.tsx
POT:
[vote-tooltip.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/3f9e2cf1-de4c-4797-b584-d20f89d0d1d5)
> Removed Create a Proposal Tooltip from Vote button

- src/components/MajorityModel.tsx
- src/config/index.ts
POT
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/40c22902-c0c0-486d-8c73-1cb1c733c2bb
> chore: change proposal duration from 5mins to 1day

- src/stores/genesisStore.ts
> BN assertion error fix

- __test__/AssetsTable.test.tsx
- src/components/Assets.tsx
- src/components/AssetsTable.tsx
[asset-filter-fix.webm](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/5f898b4d-d4eb-4112-9c93-e52447b22e89)
> Asset Holding Filter and Layout fix

- src/components/ExploreDaos.tsx
- src/stores/genesisStore.ts
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/b966facc-d1a7-4eaf-b10b-997deca4ddbd
> No Results Copy Onload fix

- src/components/Assets.tsx
POT:
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/f6cfcb74-ea97-484d-a939-4d16d427a4a7
> Case-insensitive client side search

- src/components/CreateProposal.tsx
- src/components/MultisigTransactionAccordion.tsx
- src/components/Transactions.tsx
- fixed new proposal input ui overlap 
- fixed transactions client side filter
https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/137761725/3baf13bf-b0ba-4ecd-817c-8e55549e4de9
- checked visiting dao connected with 0 balance
> Regression Testing 24.08.2023 Part 1

- src/components/ChangeDaoOwner.tsx
- src/components/Governance.tsx
- src/components/MultisigTransactionAccordion.tsx
- src/components/Transactions.tsx
- src/components/TransferTreasuryAsset.tsx
- reload multisig transaction and badgecount on successful approval or cancel
- reload multisig pending transaction badge count on governance txx
- hide cancel button for CANCELLED multisig tnx
> Reload Multisig Transactions

- src/components/Assets.tsx
- src/components/DaoDashboard.tsx
- src/components/TransferAssetModal.tsx
- src/pages/account/index.tsx
- src/services/assets.ts
- src/stores/account.ts
- src/stores/genesisStore.ts
- src/utils/transformer.ts
convert params to camelcase and transform responses to camelcase
> asset service: transform snakecase to camelcase

- __test__/AssetHoldingCard.test.tsx
- __test__/AssetsTable.test.tsx
- __test__/TransferAssetModal.test.tsx
- src/components/AssetHoldingCard.tsx
- src/components/AssetsTable.tsx
- src/components/TransferAssetModal.tsx
- src/components/TransferForm.tsx
- src/services/assets.ts
- src/stores/genesisStore.ts
- src/utils/number.ts
- src/utils/transformer.ts
- added util that converts values greater the polkadot/util value into BN
- convert asset balances in services
- use util in genesisStore
> Big number conversion check

- __test__/GovernanceForm.test.tsx
- src/components/GovernanceForm.tsx
> Governance Config Screen Update
